CREATE TYPE "Role" AS ENUM ('EMPLOYEE', 'TEAM_LEADER', 'HR');
CREATE TYPE "WorkMode" AS ENUM ('OFFICE', 'WFH');
CREATE TYPE "AttendanceStatus" AS ENUM ('WORKING', 'COMPLETED');
CREATE TYPE "LeaveType" AS ENUM ('VACATION', 'SICK', 'PERSONAL');
CREATE TYPE "LeaveStatus" AS ENUM ('PENDING_LEADER', 'PENDING_HR', 'APPROVED', 'REJECTED');
CREATE TYPE "ApprovalDecision" AS ENUM ('APPROVED', 'REJECTED', 'CHANGES_REQUESTED');
CREATE TYPE "TaskStatus" AS ENUM ('TODO', 'IN_PROGRESS', 'SUBMITTED', 'DONE');
CREATE TYPE "Priority" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TYPE "AudienceType" AS ENUM ('EVERYONE', 'TEAM', 'ROLE');
CREATE TYPE "OfficeRoom" AS ENUM ('WORK_AREA', 'MEETING_A', 'MEETING_B', 'LOUNGE', 'OFFLINE');

CREATE TABLE "Department" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Department_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Team" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Team_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "displayName" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'EMPLOYEE', "departmentId" TEXT NOT NULL, "teamId" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Attendance" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "workMode" "WorkMode" NOT NULL, "status" "AttendanceStatus" NOT NULL DEFAULT 'WORKING', "photoPath" TEXT, "checkedIn" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "checkedOut" TIMESTAMP(3), CONSTRAINT "Attendance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LeaveRequest" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" "LeaveType" NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3) NOT NULL, "days" INTEGER NOT NULL, "reason" TEXT NOT NULL, "status" "LeaveStatus" NOT NULL DEFAULT 'PENDING_LEADER', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "LeaveRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LeaveApproval" ("id" TEXT NOT NULL, "requestId" TEXT NOT NULL, "reviewerId" TEXT NOT NULL, "reviewerRole" "Role" NOT NULL, "decision" "ApprovalDecision" NOT NULL, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LeaveApproval_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Task" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "priority" "Priority" NOT NULL DEFAULT 'MEDIUM', "status" "TaskStatus" NOT NULL DEFAULT 'TODO', "dueAt" TIMESTAMP(3), "createdById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Task_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaskAssignee" ("taskId" TEXT NOT NULL, "userId" TEXT NOT NULL, CONSTRAINT "TaskAssignee_pkey" PRIMARY KEY ("taskId","userId"));
CREATE TABLE "TaskSubmission" ("id" TEXT NOT NULL, "taskId" TEXT NOT NULL, "submitterId" TEXT NOT NULL, "note" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TaskSubmission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaskApproval" ("id" TEXT NOT NULL, "submissionId" TEXT NOT NULL, "reviewerId" TEXT NOT NULL, "decision" "ApprovalDecision" NOT NULL, "note" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TaskApproval_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Announcement" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "authorId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Announcement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AnnouncementAudience" ("id" TEXT NOT NULL, "announcementId" TEXT NOT NULL, "type" "AudienceType" NOT NULL, "teamId" TEXT, "role" "Role", CONSTRAINT "AnnouncementAudience_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OfficePresence" ("userId" TEXT NOT NULL, "room" "OfficeRoom" NOT NULL DEFAULT 'OFFLINE', "x" DOUBLE PRECISION NOT NULL DEFAULT 0, "y" DOUBLE PRECISION NOT NULL DEFAULT 0, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "OfficePresence_pkey" PRIMARY KEY ("userId"));

CREATE UNIQUE INDEX "Department_name_key" ON "Department"("name");
CREATE UNIQUE INDEX "Team_name_key" ON "Team"("name");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "Attendance_userId_checkedIn_idx" ON "Attendance"("userId", "checkedIn");

ALTER TABLE "User" ADD CONSTRAINT "User_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LeaveApproval" ADD CONSTRAINT "LeaveApproval_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "LeaveRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LeaveApproval" ADD CONSTRAINT "LeaveApproval_reviewerId_fkey" FOREIGN KEY ("reviewerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskAssignee" ADD CONSTRAINT "TaskAssignee_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaskAssignee" ADD CONSTRAINT "TaskAssignee_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskSubmission" ADD CONSTRAINT "TaskSubmission_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskSubmission" ADD CONSTRAINT "TaskSubmission_submitterId_fkey" FOREIGN KEY ("submitterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskApproval" ADD CONSTRAINT "TaskApproval_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "TaskSubmission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TaskApproval" ADD CONSTRAINT "TaskApproval_reviewerId_fkey" FOREIGN KEY ("reviewerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AnnouncementAudience" ADD CONSTRAINT "AnnouncementAudience_announcementId_fkey" FOREIGN KEY ("announcementId") REFERENCES "Announcement"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AnnouncementAudience" ADD CONSTRAINT "AnnouncementAudience_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OfficePresence" ADD CONSTRAINT "OfficePresence_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
